language: minimal
services: docker
env:
  - DOCKER_COMPOSE_VERSION=1.23.2
before_install:
  - docker -v && docker-compose -v
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
  - curl -LO https://storage.googleapis.com/kubernetes-release/release/$(curl -s https://storage.googleapis.com/kubernetes-release/release/stable.txt)/bin/linux/amd64/kubectl
  - chmod +x ./kubectl
  - sudo mv ./kubectl /usr/local/bin/kubectl
  - mkdir ${HOME}/.kube
  - echo "$KUBE_CONFIG" | base64 --decode > ${HOME}/.kube/config # include to travis console env variable :cat ${HOME}/.kube/config | base64 | pbcopy
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin # set Docker username and password in Travis console
  - echo 'dockerhub credentials configured'
install:
  - docker-compose -f udacity-deployment/docker/docker-compose-build.yaml build --parallel 
  # - docker-compose -f udacity-deployment/docker/docker-compose-build.yaml push
script:
    - docker --version # print the version for logging
  
    - docker build -t udagram-restapi-feed udagram-restapi-feed 
    - docker tag udagram-restapi-feed gankush1995/udagram-feed:latest
  
    - docker build -t udagram-frontend udagram-frontend
    - docker tag udagram-frontend gankush1995/udagram-frontend:latest
  
    - docker build -t udagram-restapi-user udagram-restapi-user
    - docker tag udagram-restapi-user gankush1995/udagram-user:latest
    
    - docker build -t udagram-reverse-proxy udacity-deployment/docker
    - docker tag udagram-reverse-proxy gankush1995/udagram-reverse-proxy:latest
  
 
    - docker push gankush1995/udagram-feed
    - docker push gankush1995/udagram-frontend
    - docker push gankush1995/udagram-user
    - docker push gankush1995/udagram-reverse-proxy